### ISSUE TITLE
export includes outdated entries

### ISSUE THREAD

**Issue by jonasvaneyck** [garrettdowd/splitwise_export#1]
Hi there! 
I absolutely LOVE the export feature. very easy to set up, and also very fast to use. i use it all the time to manage the expenses o a big project ( 700 000 EUR) so pretty happy with it! 

One thing is challenging: the export doesnt match the latest version of my splitwise content. that means that if I delete an entry, the export will still show this entry in the expense export. 

another feature would also be great: now the date in the export is the date of latest modification. it would be nice if it is the date of entry, you think that is possible? 

anyways thanks so so much for sharing this script!!

**Comment by garrettdowd** [comment]
Its great to hear you find it valuable! I have not used the script recently, but I do remember that Splitwise would include deleted transactions via their API. I will take a look at this and get back to you.

**Comment by garrettdowd** [comment]
It should not be downloading deleted expenses unless you explicitly tell it to. Here is an example of when I run the script
```
python splitwise_export.py
0: Non-group expenses
1: Group1
2: Group2
Export data for which group? Enter the number here:
2
Enter filename. Leave blank for default. File will be saved in current directory
test.csv
Include deleted expenses?
 (y/N): y
```
When it asks `Include deleted expenses?` you should have to explicitly specify `y` or `yes` for it to include deleted expenses (the csv will include a new column and specify who deleted the expense). If you just press Return/Enter then the default option is No and it will not include deleted expenses.

If it is not asking you that question then you may have an old version? Otherwise, can you run the script with both option (yes and no) for `Include deleted expenses?` and compare the results? At the moment I don't have enough info to investigate further because it is working as expected on my end.

**Comment by garrettdowd** [comment]
I am also not able to reproduce your export date problem. Even after changing details about an expense it still gives/exports the date as the date of creation/entry. This may have to do with an ambiguity in the Splitwise API.

If you continue to have this problem please create a new issue and provide any other details you think are relevant (including splitwise version `pip show splitwise`). I would need to read up more heavily on the Splitwise API.

**Comment by jonasvaneyck** [comment]
Hi Garrett, 
Thank you for the quick reply. the problem is indeed fixed by using your latest script, i was doing something (stupid) wrong at my end but thats now solved.  thanks a lot, massive improvement again for me :) 

thanks or sharing. strange splitwise doesnt offer this feature, its really handy to share a table with clickable links to the receipts

**Comment by garrettdowd** [comment]
Thanks for your feedback. Feel free to open new issues for any other bugs or feature requests! I am now going to mark this closed.
